name: 'Check pull request info'
description: 'Check the body and title of the pr against a regex pattern'
author: 'Valence'
inputs:
  body:
    description: 'body of pr in json format'
    required: true
  title:
    description: 'title of pr in json format'
    required: true

  body_pattern:
    description: 'A regex pattern to check if the pr body is valid.'
    required: true
  title_pattern:
    description: 'A regex pattern to check if the pr body is valid.'
    required: true
  body_flags:
    description: 'Expression flags change how the expression is interpreted.'
    required: false
    default: ''
  title_flags:
    description: 'Expression flags change how the expression is interpreted.'
    required: false
    default: ''
  error:
    description: 'A error message which will be returned in case of an error.'
    required: true
  pre_error:
    description: 'A error message which will be showed in the begin of errors.'
    required: false
    default: ''
  post_error:
    description: 'A error message which will be showed in the end of errors.'
    required: false
    default: ''

runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'check'
  color: 'blue'
